In [2]:
import os
os.environ['KAGGLE_CONFIG_DIR'] = '.'
!chmod 600 ./kaggle.json
!kaggle competitions download -c udea-ai4eng-20242

Downloading udea-ai4eng-20242.zip to /content
 65% 13.0M/20.1M [00:00<00:00, 133MB/s]
100% 20.1M/20.1M [00:00<00:00, 153MB/s]

In [3]:
!unzip udea*.zip > /dev/null

In [4]:
import pandas as pd
import numpy as np

z = pd.read_csv("train.csv")
print ("shape of loaded dataframe", z.shape)

shape of loaded dataframe (692500, 12)

In [5]:
z.head()

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_EDUCACIONMADRE,ESTU_PAGOMATRICULAPROPIO,RENDIMIENTO_GLOBAL
0,904256,20212,ENFERMERIA,BOGOTÁ,Entre 5.5 millones y menos de 7 millones,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica incompleta,Postgrado,No,medio-alto
1,645256,20212,DERECHO,ATLANTICO,Entre 2.5 millones y menos de 4 millones,0,Estrato 3,No,Técnica o tecnológica completa,Técnica o tecnológica incompleta,No,bajo
2,308367,20203,MERCADEO Y PUBLICIDAD,BOGOTÁ,Entre 2.5 millones y menos de 4 millones,Más de 30 horas,Estrato 3,Si,Secundaria (Bachillerato) completa,Secundaria (Bachillerato) completa,No,bajo
3,470353,20195,ADMINISTRACION DE EMPRESAS,SANTANDER,Entre 4 millones y menos de 5.5 millones,0,Estrato 4,Si,No sabe,Secundaria (Bachillerato) completa,No,alto
4,989032,20212,PSICOLOGIA,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 3,Si,Primaria completa,Primaria completa,No,medio-bajo

In [9]:
students_for_career = z['ESTU_PRGM_ACADEMICO'].value_counts()
students_for_career.head()

ESTU_PRGM_ACADEMICO
DERECHO                       53244
ADMINISTRACION DE EMPRESAS    51902
CONTADURIA PUBLICA            39664
PSICOLOGIA                    31932
INGENIERIA INDUSTRIAL         28481
Name: count, dtype: int64

In [8]:
students_for_department = z['ESTU_PRGM_DEPARTAMENTO'].value_counts()
students_for_department.head()

ESTU_PRGM_DEPARTAMENTO
BOGOTÁ       282159
ANTIOQUIA     83607
VALLE         44588
ATLANTICO     41020
SANTANDER     28828
Name: count, dtype: int64

In [10]:
students_for_department = z['FAMI_ESTRATOVIVIENDA'].value_counts()
students_for_department.head()

FAMI_ESTRATOVIVIENDA
Estrato 2    232671
Estrato 3    210685
Estrato 1    111991
Estrato 4     65514
Estrato 5     23608
Name: count, dtype: int64